### ISSUE TITLE
Status of the data

### ISSUE THREAD

**Issue by LinguList** [lexibank/yanglalo#1]
The data is based on a glossary in PDF, which is, however, not easy to digitize. The author shared a spreadsheet with me in the past, with extended data, which we should not share online. 

My idea is: take only the languages explicitly mentioned in the official publication (about 8) and extract them from the spreadsheet. Otherwise it would be unfair for the author (and we'd have a hardtime to find sources for the data).

**Comment by LinguList** [comment]
[concepts-mapped.xlsx](https://github.com/lexibank/yanglalo/files/2796107/concepts-mapped.xlsx)

We're talking about a rather long list of concepts here. Teh concepts attached have been checked as part of the student task.

**Comment by tresoldi** [comment]
The immediate task is thus to check the concepts by referring to source, i.e., [this](https://www.sil.org/system/files/reapdata/45/63/47/45634767234331504727329755903316120678/Yang_Lalo_Sept_2011.pdf)?

The PDF looks to have been generated in a proper way, so it should not be extremely difficult to parse its textual conversion.

I will be working on the conceptlist meanwhile.

**Comment by LinguList** [comment]
You saw all the material I sent you, right? If there are more questions, have a look there. I sent two emails on this last week, I think. Will check them if I'm in the office (bout 30 min).

**Comment by chrzyki** [comment]
Dataset is done.
